name: Image test

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag flask_app:$(date +%s)
     - name: List images
       run: docker images
     - name: Publish the image
      run: echo "publish docker"
